// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

public final class Mode {
  private Mode() { }
  public static final byte NONE = 0;
  public static final byte Foot = 1;
  public static final byte Bike = 2;

  private static final String[] names = { "NONE", "Foot", "Bike", };

  public static String name(int e) { return names[e]; }
};

