// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class MsgContent {
  private MsgContent() { }
  public static final byte NONE = 0;
  public static final byte MotisNoMessage = 1;
  public static final byte MotisError = 2;
  public static final byte MotisSuccess = 3;
  public static final byte HTTPRequest = 4;
  public static final byte HTTPResponse = 5;
  public static final byte BikesharingRequest = 6;
  public static final byte BikesharingResponse = 7;
  public static final byte BikesharingGeoTerminalsRequest = 8;
  public static final byte BikesharingGeoTerminalsResponse = 9;
  public static final byte StationGuesserRequest = 10;
  public static final byte StationGuesserResponse = 11;
  public static final byte IntermodalRoutingRequest = 12;
  public static final byte LookupGeoStationIdRequest = 13;
  public static final byte LookupGeoStationRequest = 14;
  public static final byte LookupGeoStationResponse = 15;
  public static final byte LookupBatchGeoStationRequest = 16;
  public static final byte LookupBatchGeoStationResponse = 17;
  public static final byte LookupStationEventsRequest = 18;
  public static final byte LookupStationEventsResponse = 19;
  public static final byte LookupScheduleInfoResponse = 20;
  public static final byte LookupMetaStationRequest = 21;
  public static final byte LookupMetaStationResponse = 22;
  public static final byte LookupBatchMetaStationRequest = 23;
  public static final byte LookupBatchMetaStationResponse = 24;
  public static final byte LookupIdTrainRequest = 25;
  public static final byte LookupIdTrainResponse = 26;
  public static final byte RoutesSectionReq = 27;
  public static final byte RoutesSectionRes = 28;
  public static final byte RoutesAllSectionReq = 29;
  public static final byte RoutesAllSectionRes = 30;
  public static final byte RailVizInit = 31;
  public static final byte RailVizAlltraReq = 32;
  public static final byte RailVizAlltraRes = 33;
  public static final byte RailVizStationDetailReq = 34;
  public static final byte RailVizStationDetailRes = 35;
  public static final byte RailVizRouteAtTimeReq = 36;
  public static final byte RailVizRouteAtTimeRes = 37;
  public static final byte RailVizFindTrain = 38;
  public static final byte OSRMOneToManyRequest = 39;
  public static final byte OSRMOneToManyResponse = 40;
  public static final byte OSRMViaRouteRequest = 41;
  public static final byte OSRMViaRouteResponse = 42;
  public static final byte ReliableRoutingRequest = 43;
  public static final byte ReliableRoutingResponse = 44;
  public static final byte ReliabilityRatingResponse = 45;
  public static final byte RISBatch = 46;
  public static final byte RISForwardTimeRequest = 47;
  public static final byte RoutingRequest = 48;
  public static final byte RoutingResponse = 49;
  public static final byte RtUpdate = 50;
  public static final byte UserRegisterRequest = 51;

  private static final String[] names = { "NONE", "MotisNoMessage", "MotisError", "MotisSuccess", "HTTPRequest", "HTTPResponse", "BikesharingRequest", "BikesharingResponse", "BikesharingGeoTerminalsRequest", "BikesharingGeoTerminalsResponse", "StationGuesserRequest", "StationGuesserResponse", "IntermodalRoutingRequest", "LookupGeoStationIdRequest", "LookupGeoStationRequest", "LookupGeoStationResponse", "LookupBatchGeoStationRequest", "LookupBatchGeoStationResponse", "LookupStationEventsRequest", "LookupStationEventsResponse", "LookupScheduleInfoResponse", "LookupMetaStationRequest", "LookupMetaStationResponse", "LookupBatchMetaStationRequest", "LookupBatchMetaStationResponse", "LookupIdTrainRequest", "LookupIdTrainResponse", "RoutesSectionReq", "RoutesSectionRes", "RoutesAllSectionReq", "RoutesAllSectionRes", "RailVizInit", "RailVizAlltraReq", "RailVizAlltraRes", "RailVizStationDetailReq", "RailVizStationDetailRes", "RailVizRouteAtTimeReq", "RailVizRouteAtTimeRes", "RailVizFindTrain", "OSRMOneToManyRequest", "OSRMOneToManyResponse", "OSRMViaRouteRequest", "OSRMViaRouteResponse", "ReliableRoutingRequest", "ReliableRoutingResponse", "ReliabilityRatingResponse", "RISBatch", "RISForwardTimeRequest", "RoutingRequest", "RoutingResponse", "RtUpdate", "UserRegisterRequest", };

  public static String name(int e) { return names[e]; }
};

