// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class MsgContent {
  private MsgContent() { }
  public static final byte NONE = 0;
  public static final byte MotisNoMessage = 1;
  public static final byte MotisError = 2;
  public static final byte MotisSuccess = 3;
  public static final byte HTTPRequest = 4;
  public static final byte HTTPResponse = 5;
  public static final byte BikesharingRequest = 6;
  public static final byte BikesharingResponse = 7;
  public static final byte BikesharingGeoTerminalsRequest = 8;
  public static final byte BikesharingGeoTerminalsResponse = 9;
  public static final byte StationGuesserRequest = 10;
  public static final byte StationGuesserResponse = 11;
  public static final byte IntermodalRoutingRequest = 12;
  public static final byte IntermodalRoutingResponse = 13;
  public static final byte LookupGeoStationIdRequest = 14;
  public static final byte LookupGeoStationRequest = 15;
  public static final byte LookupGeoStationResponse = 16;
  public static final byte LookupBatchGeoStationRequest = 17;
  public static final byte LookupBatchGeoStationResponse = 18;
  public static final byte LookupStationEventsRequest = 19;
  public static final byte LookupStationEventsResponse = 20;
  public static final byte LookupScheduleInfoResponse = 21;
  public static final byte LookupMetaStationRequest = 22;
  public static final byte LookupMetaStationResponse = 23;
  public static final byte LookupBatchMetaStationRequest = 24;
  public static final byte LookupBatchMetaStationResponse = 25;
  public static final byte LookupIdTrainRequest = 26;
  public static final byte LookupIdTrainResponse = 27;
  public static final byte RoutesIdTrainRequest = 28;
  public static final byte RoutesIdTrainResponse = 29;
  public static final byte RailVizInit = 30;
  public static final byte RailVizAlltraReq = 31;
  public static final byte RailVizAlltraRes = 32;
  public static final byte RailVizStationDetailReq = 33;
  public static final byte RailVizStationDetailRes = 34;
  public static final byte RailVizRouteAtTimeReq = 35;
  public static final byte RailVizRouteAtTimeRes = 36;
  public static final byte RailVizFindTrain = 37;
  public static final byte OSRMOneToManyRequest = 38;
  public static final byte OSRMOneToManyResponse = 39;
  public static final byte OSRMViaRouteRequest = 40;
  public static final byte OSRMViaRouteResponse = 41;
  public static final byte OSRMSmoothViaRouteRequest = 42;
  public static final byte OSRMSmoothViaRouteResponse = 43;
  public static final byte ReliableRoutingRequest = 44;
  public static final byte ReliableRoutingResponse = 45;
  public static final byte ReliabilityRatingResponse = 46;
  public static final byte RISBatch = 47;
  public static final byte RISForwardTimeRequest = 48;
  public static final byte RoutingRequest = 49;
  public static final byte RoutingResponse = 50;
  public static final byte RtUpdate = 51;

  private static final String[] names = { "NONE", "MotisNoMessage", "MotisError", "MotisSuccess", "HTTPRequest", "HTTPResponse", "BikesharingRequest", "BikesharingResponse", "BikesharingGeoTerminalsRequest", "BikesharingGeoTerminalsResponse", "StationGuesserRequest", "StationGuesserResponse", "IntermodalRoutingRequest", "IntermodalRoutingResponse", "LookupGeoStationIdRequest", "LookupGeoStationRequest", "LookupGeoStationResponse", "LookupBatchGeoStationRequest", "LookupBatchGeoStationResponse", "LookupStationEventsRequest", "LookupStationEventsResponse", "LookupScheduleInfoResponse", "LookupMetaStationRequest", "LookupMetaStationResponse", "LookupBatchMetaStationRequest", "LookupBatchMetaStationResponse", "LookupIdTrainRequest", "LookupIdTrainResponse", "RoutesIdTrainRequest", "RoutesIdTrainResponse", "RailVizInit", "RailVizAlltraReq", "RailVizAlltraRes", "RailVizStationDetailReq", "RailVizStationDetailRes", "RailVizRouteAtTimeReq", "RailVizRouteAtTimeRes", "RailVizFindTrain", "OSRMOneToManyRequest", "OSRMOneToManyResponse", "OSRMViaRouteRequest", "OSRMViaRouteResponse", "OSRMSmoothViaRouteRequest", "OSRMSmoothViaRouteResponse", "ReliableRoutingRequest", "ReliableRoutingResponse", "ReliabilityRatingResponse", "RISBatch", "RISForwardTimeRequest", "RoutingRequest", "RoutingResponse", "RtUpdate", };

  public static String name(int e) { return names[e]; }
};

