// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebsocketService.proto

#ifndef PROTOBUF_WebsocketService_2eproto__INCLUDED
#define PROTOBUF_WebsocketService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace td {
namespace railviz {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WebsocketService_2eproto();
void protobuf_AssignDesc_WebsocketService_2eproto();
void protobuf_ShutdownFile_WebsocketService_2eproto();

class RequestPovUpdate;
class RequestAllStations;
class ResponseAllStations;
class ResponseAllStations_Station;
class RequestGetStationsInfo;
class RequestGetStationsInfo_Station;
class ResponseGetStationsInfo;
class ResponseGetStationsInfo_Station;
class RequestAllTrains;
class ResponseAllTrains;
class ResponseAllTrains_Train;
class ResponseAllTrains_Train_Station;

// ===================================================================

class RequestPovUpdate : public ::google::protobuf::Message {
 public:
  RequestPovUpdate();
  virtual ~RequestPovUpdate();

  RequestPovUpdate(const RequestPovUpdate& from);

  inline RequestPovUpdate& operator=(const RequestPovUpdate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestPovUpdate& default_instance();

  void Swap(RequestPovUpdate* other);

  // implements Message ----------------------------------------------

  RequestPovUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestPovUpdate& from);
  void MergeFrom(const RequestPovUpdate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // required float lt_latitude = 2;
  inline bool has_lt_latitude() const;
  inline void clear_lt_latitude();
  static const int kLtLatitudeFieldNumber = 2;
  inline float lt_latitude() const;
  inline void set_lt_latitude(float value);

  // required float lt_longitude = 3;
  inline bool has_lt_longitude() const;
  inline void clear_lt_longitude();
  static const int kLtLongitudeFieldNumber = 3;
  inline float lt_longitude() const;
  inline void set_lt_longitude(float value);

  // required float rb_latitude = 4;
  inline bool has_rb_latitude() const;
  inline void clear_rb_latitude();
  static const int kRbLatitudeFieldNumber = 4;
  inline float rb_latitude() const;
  inline void set_rb_latitude(float value);

  // required float rb_longitude = 5;
  inline bool has_rb_longitude() const;
  inline void clear_rb_longitude();
  static const int kRbLongitudeFieldNumber = 5;
  inline float rb_longitude() const;
  inline void set_rb_longitude(float value);

  // @@protoc_insertion_point(class_scope:td.railviz.RequestPovUpdate)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();
  inline void set_has_lt_latitude();
  inline void clear_has_lt_latitude();
  inline void set_has_lt_longitude();
  inline void clear_has_lt_longitude();
  inline void set_has_rb_latitude();
  inline void clear_has_rb_latitude();
  inline void set_has_rb_longitude();
  inline void clear_has_rb_longitude();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 protoversion_;
  float lt_latitude_;
  float lt_longitude_;
  float rb_latitude_;
  float rb_longitude_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static RequestPovUpdate* default_instance_;
};
// -------------------------------------------------------------------

class RequestAllStations : public ::google::protobuf::Message {
 public:
  RequestAllStations();
  virtual ~RequestAllStations();

  RequestAllStations(const RequestAllStations& from);

  inline RequestAllStations& operator=(const RequestAllStations& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestAllStations& default_instance();

  void Swap(RequestAllStations* other);

  // implements Message ----------------------------------------------

  RequestAllStations* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestAllStations& from);
  void MergeFrom(const RequestAllStations& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:td.railviz.RequestAllStations)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 protoversion_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static RequestAllStations* default_instance_;
};
// -------------------------------------------------------------------

class ResponseAllStations_Station : public ::google::protobuf::Message {
 public:
  ResponseAllStations_Station();
  virtual ~ResponseAllStations_Station();

  ResponseAllStations_Station(const ResponseAllStations_Station& from);

  inline ResponseAllStations_Station& operator=(const ResponseAllStations_Station& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseAllStations_Station& default_instance();

  void Swap(ResponseAllStations_Station* other);

  // implements Message ----------------------------------------------

  ResponseAllStations_Station* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseAllStations_Station& from);
  void MergeFrom(const ResponseAllStations_Station& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 stationId = 1;
  inline bool has_stationid() const;
  inline void clear_stationid();
  static const int kStationIdFieldNumber = 1;
  inline ::google::protobuf::int32 stationid() const;
  inline void set_stationid(::google::protobuf::int32 value);

  // required float station_latitude = 2;
  inline bool has_station_latitude() const;
  inline void clear_station_latitude();
  static const int kStationLatitudeFieldNumber = 2;
  inline float station_latitude() const;
  inline void set_station_latitude(float value);

  // required float station_longitude = 3;
  inline bool has_station_longitude() const;
  inline void clear_station_longitude();
  static const int kStationLongitudeFieldNumber = 3;
  inline float station_longitude() const;
  inline void set_station_longitude(float value);

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseAllStations.Station)
 private:
  inline void set_has_stationid();
  inline void clear_has_stationid();
  inline void set_has_station_latitude();
  inline void clear_has_station_latitude();
  inline void set_has_station_longitude();
  inline void clear_has_station_longitude();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 stationid_;
  float station_latitude_;
  float station_longitude_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseAllStations_Station* default_instance_;
};
// -------------------------------------------------------------------

class ResponseAllStations : public ::google::protobuf::Message {
 public:
  ResponseAllStations();
  virtual ~ResponseAllStations();

  ResponseAllStations(const ResponseAllStations& from);

  inline ResponseAllStations& operator=(const ResponseAllStations& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseAllStations& default_instance();

  void Swap(ResponseAllStations* other);

  // implements Message ----------------------------------------------

  ResponseAllStations* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseAllStations& from);
  void MergeFrom(const ResponseAllStations& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ResponseAllStations_Station Station;

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // repeated .td.railviz.ResponseAllStations.Station station = 2;
  inline int station_size() const;
  inline void clear_station();
  static const int kStationFieldNumber = 2;
  inline const ::td::railviz::ResponseAllStations_Station& station(int index) const;
  inline ::td::railviz::ResponseAllStations_Station* mutable_station(int index);
  inline ::td::railviz::ResponseAllStations_Station* add_station();
  inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllStations_Station >&
      station() const;
  inline ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllStations_Station >*
      mutable_station();

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseAllStations)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllStations_Station > station_;
  ::google::protobuf::int32 protoversion_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseAllStations* default_instance_;
};
// -------------------------------------------------------------------

class RequestGetStationsInfo_Station : public ::google::protobuf::Message {
 public:
  RequestGetStationsInfo_Station();
  virtual ~RequestGetStationsInfo_Station();

  RequestGetStationsInfo_Station(const RequestGetStationsInfo_Station& from);

  inline RequestGetStationsInfo_Station& operator=(const RequestGetStationsInfo_Station& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestGetStationsInfo_Station& default_instance();

  void Swap(RequestGetStationsInfo_Station* other);

  // implements Message ----------------------------------------------

  RequestGetStationsInfo_Station* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestGetStationsInfo_Station& from);
  void MergeFrom(const RequestGetStationsInfo_Station& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 stationId = 1;
  inline bool has_stationid() const;
  inline void clear_stationid();
  static const int kStationIdFieldNumber = 1;
  inline ::google::protobuf::int32 stationid() const;
  inline void set_stationid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:td.railviz.RequestGetStationsInfo.Station)
 private:
  inline void set_has_stationid();
  inline void clear_has_stationid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 stationid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static RequestGetStationsInfo_Station* default_instance_;
};
// -------------------------------------------------------------------

class RequestGetStationsInfo : public ::google::protobuf::Message {
 public:
  RequestGetStationsInfo();
  virtual ~RequestGetStationsInfo();

  RequestGetStationsInfo(const RequestGetStationsInfo& from);

  inline RequestGetStationsInfo& operator=(const RequestGetStationsInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestGetStationsInfo& default_instance();

  void Swap(RequestGetStationsInfo* other);

  // implements Message ----------------------------------------------

  RequestGetStationsInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestGetStationsInfo& from);
  void MergeFrom(const RequestGetStationsInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RequestGetStationsInfo_Station Station;

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // repeated .td.railviz.RequestGetStationsInfo.Station station = 2;
  inline int station_size() const;
  inline void clear_station();
  static const int kStationFieldNumber = 2;
  inline const ::td::railviz::RequestGetStationsInfo_Station& station(int index) const;
  inline ::td::railviz::RequestGetStationsInfo_Station* mutable_station(int index);
  inline ::td::railviz::RequestGetStationsInfo_Station* add_station();
  inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::RequestGetStationsInfo_Station >&
      station() const;
  inline ::google::protobuf::RepeatedPtrField< ::td::railviz::RequestGetStationsInfo_Station >*
      mutable_station();

  // @@protoc_insertion_point(class_scope:td.railviz.RequestGetStationsInfo)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::td::railviz::RequestGetStationsInfo_Station > station_;
  ::google::protobuf::int32 protoversion_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static RequestGetStationsInfo* default_instance_;
};
// -------------------------------------------------------------------

class ResponseGetStationsInfo_Station : public ::google::protobuf::Message {
 public:
  ResponseGetStationsInfo_Station();
  virtual ~ResponseGetStationsInfo_Station();

  ResponseGetStationsInfo_Station(const ResponseGetStationsInfo_Station& from);

  inline ResponseGetStationsInfo_Station& operator=(const ResponseGetStationsInfo_Station& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseGetStationsInfo_Station& default_instance();

  void Swap(ResponseGetStationsInfo_Station* other);

  // implements Message ----------------------------------------------

  ResponseGetStationsInfo_Station* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseGetStationsInfo_Station& from);
  void MergeFrom(const ResponseGetStationsInfo_Station& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseGetStationsInfo.Station)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseGetStationsInfo_Station* default_instance_;
};
// -------------------------------------------------------------------

class ResponseGetStationsInfo : public ::google::protobuf::Message {
 public:
  ResponseGetStationsInfo();
  virtual ~ResponseGetStationsInfo();

  ResponseGetStationsInfo(const ResponseGetStationsInfo& from);

  inline ResponseGetStationsInfo& operator=(const ResponseGetStationsInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseGetStationsInfo& default_instance();

  void Swap(ResponseGetStationsInfo* other);

  // implements Message ----------------------------------------------

  ResponseGetStationsInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseGetStationsInfo& from);
  void MergeFrom(const ResponseGetStationsInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ResponseGetStationsInfo_Station Station;

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // repeated .td.railviz.ResponseGetStationsInfo.Station station = 2;
  inline int station_size() const;
  inline void clear_station();
  static const int kStationFieldNumber = 2;
  inline const ::td::railviz::ResponseGetStationsInfo_Station& station(int index) const;
  inline ::td::railviz::ResponseGetStationsInfo_Station* mutable_station(int index);
  inline ::td::railviz::ResponseGetStationsInfo_Station* add_station();
  inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseGetStationsInfo_Station >&
      station() const;
  inline ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseGetStationsInfo_Station >*
      mutable_station();

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseGetStationsInfo)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseGetStationsInfo_Station > station_;
  ::google::protobuf::int32 protoversion_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseGetStationsInfo* default_instance_;
};
// -------------------------------------------------------------------

class RequestAllTrains : public ::google::protobuf::Message {
 public:
  RequestAllTrains();
  virtual ~RequestAllTrains();

  RequestAllTrains(const RequestAllTrains& from);

  inline RequestAllTrains& operator=(const RequestAllTrains& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestAllTrains& default_instance();

  void Swap(RequestAllTrains* other);

  // implements Message ----------------------------------------------

  RequestAllTrains* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestAllTrains& from);
  void MergeFrom(const RequestAllTrains& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:td.railviz.RequestAllTrains)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 protoversion_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static RequestAllTrains* default_instance_;
};
// -------------------------------------------------------------------

class ResponseAllTrains_Train_Station : public ::google::protobuf::Message {
 public:
  ResponseAllTrains_Train_Station();
  virtual ~ResponseAllTrains_Train_Station();

  ResponseAllTrains_Train_Station(const ResponseAllTrains_Train_Station& from);

  inline ResponseAllTrains_Train_Station& operator=(const ResponseAllTrains_Train_Station& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseAllTrains_Train_Station& default_instance();

  void Swap(ResponseAllTrains_Train_Station* other);

  // implements Message ----------------------------------------------

  ResponseAllTrains_Train_Station* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseAllTrains_Train_Station& from);
  void MergeFrom(const ResponseAllTrains_Train_Station& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required float latitude = 2;
  inline bool has_latitude() const;
  inline void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  inline float latitude() const;
  inline void set_latitude(float value);

  // required float longitude = 3;
  inline bool has_longitude() const;
  inline void clear_longitude();
  static const int kLongitudeFieldNumber = 3;
  inline float longitude() const;
  inline void set_longitude(float value);

  // required int32 time = 4;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 4;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseAllTrains.Train.Station)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_latitude();
  inline void clear_has_latitude();
  inline void set_has_longitude();
  inline void clear_has_longitude();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  float latitude_;
  float longitude_;
  ::google::protobuf::int32 time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseAllTrains_Train_Station* default_instance_;
};
// -------------------------------------------------------------------

class ResponseAllTrains_Train : public ::google::protobuf::Message {
 public:
  ResponseAllTrains_Train();
  virtual ~ResponseAllTrains_Train();

  ResponseAllTrains_Train(const ResponseAllTrains_Train& from);

  inline ResponseAllTrains_Train& operator=(const ResponseAllTrains_Train& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseAllTrains_Train& default_instance();

  void Swap(ResponseAllTrains_Train* other);

  // implements Message ----------------------------------------------

  ResponseAllTrains_Train* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseAllTrains_Train& from);
  void MergeFrom(const ResponseAllTrains_Train& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ResponseAllTrains_Train_Station Station;

  // accessors -------------------------------------------------------

  // required .td.railviz.ResponseAllTrains.Train.Station start = 1;
  inline bool has_start() const;
  inline void clear_start();
  static const int kStartFieldNumber = 1;
  inline const ::td::railviz::ResponseAllTrains_Train_Station& start() const;
  inline ::td::railviz::ResponseAllTrains_Train_Station* mutable_start();
  inline ::td::railviz::ResponseAllTrains_Train_Station* release_start();
  inline void set_allocated_start(::td::railviz::ResponseAllTrains_Train_Station* start);

  // required .td.railviz.ResponseAllTrains.Train.Station end = 2;
  inline bool has_end() const;
  inline void clear_end();
  static const int kEndFieldNumber = 2;
  inline const ::td::railviz::ResponseAllTrains_Train_Station& end() const;
  inline ::td::railviz::ResponseAllTrains_Train_Station* mutable_end();
  inline ::td::railviz::ResponseAllTrains_Train_Station* release_end();
  inline void set_allocated_end(::td::railviz::ResponseAllTrains_Train_Station* end);

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseAllTrains.Train)
 private:
  inline void set_has_start();
  inline void clear_has_start();
  inline void set_has_end();
  inline void clear_has_end();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::td::railviz::ResponseAllTrains_Train_Station* start_;
  ::td::railviz::ResponseAllTrains_Train_Station* end_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseAllTrains_Train* default_instance_;
};
// -------------------------------------------------------------------

class ResponseAllTrains : public ::google::protobuf::Message {
 public:
  ResponseAllTrains();
  virtual ~ResponseAllTrains();

  ResponseAllTrains(const ResponseAllTrains& from);

  inline ResponseAllTrains& operator=(const ResponseAllTrains& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseAllTrains& default_instance();

  void Swap(ResponseAllTrains* other);

  // implements Message ----------------------------------------------

  ResponseAllTrains* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseAllTrains& from);
  void MergeFrom(const ResponseAllTrains& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ResponseAllTrains_Train Train;

  // accessors -------------------------------------------------------

  // required int32 protoVersion = 1;
  inline bool has_protoversion() const;
  inline void clear_protoversion();
  static const int kProtoVersionFieldNumber = 1;
  inline ::google::protobuf::int32 protoversion() const;
  inline void set_protoversion(::google::protobuf::int32 value);

  // required int32 currentTime = 2;
  inline bool has_currenttime() const;
  inline void clear_currenttime();
  static const int kCurrentTimeFieldNumber = 2;
  inline ::google::protobuf::int32 currenttime() const;
  inline void set_currenttime(::google::protobuf::int32 value);

  // repeated .td.railviz.ResponseAllTrains.Train trains = 3;
  inline int trains_size() const;
  inline void clear_trains();
  static const int kTrainsFieldNumber = 3;
  inline const ::td::railviz::ResponseAllTrains_Train& trains(int index) const;
  inline ::td::railviz::ResponseAllTrains_Train* mutable_trains(int index);
  inline ::td::railviz::ResponseAllTrains_Train* add_trains();
  inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllTrains_Train >&
      trains() const;
  inline ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllTrains_Train >*
      mutable_trains();

  // @@protoc_insertion_point(class_scope:td.railviz.ResponseAllTrains)
 private:
  inline void set_has_protoversion();
  inline void clear_has_protoversion();
  inline void set_has_currenttime();
  inline void clear_has_currenttime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 protoversion_;
  ::google::protobuf::int32 currenttime_;
  ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllTrains_Train > trains_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_WebsocketService_2eproto();
  friend void protobuf_AssignDesc_WebsocketService_2eproto();
  friend void protobuf_ShutdownFile_WebsocketService_2eproto();

  void InitAsDefaultInstance();
  static ResponseAllTrains* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestPovUpdate

// required int32 protoVersion = 1;
inline bool RequestPovUpdate::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestPovUpdate::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestPovUpdate::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestPovUpdate::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 RequestPovUpdate::protoversion() const {
  return protoversion_;
}
inline void RequestPovUpdate::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// required float lt_latitude = 2;
inline bool RequestPovUpdate::has_lt_latitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestPovUpdate::set_has_lt_latitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestPovUpdate::clear_has_lt_latitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestPovUpdate::clear_lt_latitude() {
  lt_latitude_ = 0;
  clear_has_lt_latitude();
}
inline float RequestPovUpdate::lt_latitude() const {
  return lt_latitude_;
}
inline void RequestPovUpdate::set_lt_latitude(float value) {
  set_has_lt_latitude();
  lt_latitude_ = value;
}

// required float lt_longitude = 3;
inline bool RequestPovUpdate::has_lt_longitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestPovUpdate::set_has_lt_longitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestPovUpdate::clear_has_lt_longitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestPovUpdate::clear_lt_longitude() {
  lt_longitude_ = 0;
  clear_has_lt_longitude();
}
inline float RequestPovUpdate::lt_longitude() const {
  return lt_longitude_;
}
inline void RequestPovUpdate::set_lt_longitude(float value) {
  set_has_lt_longitude();
  lt_longitude_ = value;
}

// required float rb_latitude = 4;
inline bool RequestPovUpdate::has_rb_latitude() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestPovUpdate::set_has_rb_latitude() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestPovUpdate::clear_has_rb_latitude() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestPovUpdate::clear_rb_latitude() {
  rb_latitude_ = 0;
  clear_has_rb_latitude();
}
inline float RequestPovUpdate::rb_latitude() const {
  return rb_latitude_;
}
inline void RequestPovUpdate::set_rb_latitude(float value) {
  set_has_rb_latitude();
  rb_latitude_ = value;
}

// required float rb_longitude = 5;
inline bool RequestPovUpdate::has_rb_longitude() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RequestPovUpdate::set_has_rb_longitude() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RequestPovUpdate::clear_has_rb_longitude() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RequestPovUpdate::clear_rb_longitude() {
  rb_longitude_ = 0;
  clear_has_rb_longitude();
}
inline float RequestPovUpdate::rb_longitude() const {
  return rb_longitude_;
}
inline void RequestPovUpdate::set_rb_longitude(float value) {
  set_has_rb_longitude();
  rb_longitude_ = value;
}

// -------------------------------------------------------------------

// RequestAllStations

// required int32 protoVersion = 1;
inline bool RequestAllStations::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestAllStations::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestAllStations::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestAllStations::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 RequestAllStations::protoversion() const {
  return protoversion_;
}
inline void RequestAllStations::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// -------------------------------------------------------------------

// ResponseAllStations_Station

// required int32 stationId = 1;
inline bool ResponseAllStations_Station::has_stationid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseAllStations_Station::set_has_stationid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseAllStations_Station::clear_has_stationid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseAllStations_Station::clear_stationid() {
  stationid_ = 0;
  clear_has_stationid();
}
inline ::google::protobuf::int32 ResponseAllStations_Station::stationid() const {
  return stationid_;
}
inline void ResponseAllStations_Station::set_stationid(::google::protobuf::int32 value) {
  set_has_stationid();
  stationid_ = value;
}

// required float station_latitude = 2;
inline bool ResponseAllStations_Station::has_station_latitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseAllStations_Station::set_has_station_latitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseAllStations_Station::clear_has_station_latitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseAllStations_Station::clear_station_latitude() {
  station_latitude_ = 0;
  clear_has_station_latitude();
}
inline float ResponseAllStations_Station::station_latitude() const {
  return station_latitude_;
}
inline void ResponseAllStations_Station::set_station_latitude(float value) {
  set_has_station_latitude();
  station_latitude_ = value;
}

// required float station_longitude = 3;
inline bool ResponseAllStations_Station::has_station_longitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ResponseAllStations_Station::set_has_station_longitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ResponseAllStations_Station::clear_has_station_longitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ResponseAllStations_Station::clear_station_longitude() {
  station_longitude_ = 0;
  clear_has_station_longitude();
}
inline float ResponseAllStations_Station::station_longitude() const {
  return station_longitude_;
}
inline void ResponseAllStations_Station::set_station_longitude(float value) {
  set_has_station_longitude();
  station_longitude_ = value;
}

// -------------------------------------------------------------------

// ResponseAllStations

// required int32 protoVersion = 1;
inline bool ResponseAllStations::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseAllStations::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseAllStations::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseAllStations::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 ResponseAllStations::protoversion() const {
  return protoversion_;
}
inline void ResponseAllStations::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// repeated .td.railviz.ResponseAllStations.Station station = 2;
inline int ResponseAllStations::station_size() const {
  return station_.size();
}
inline void ResponseAllStations::clear_station() {
  station_.Clear();
}
inline const ::td::railviz::ResponseAllStations_Station& ResponseAllStations::station(int index) const {
  return station_.Get(index);
}
inline ::td::railviz::ResponseAllStations_Station* ResponseAllStations::mutable_station(int index) {
  return station_.Mutable(index);
}
inline ::td::railviz::ResponseAllStations_Station* ResponseAllStations::add_station() {
  return station_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllStations_Station >&
ResponseAllStations::station() const {
  return station_;
}
inline ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllStations_Station >*
ResponseAllStations::mutable_station() {
  return &station_;
}

// -------------------------------------------------------------------

// RequestGetStationsInfo_Station

// required int32 stationId = 1;
inline bool RequestGetStationsInfo_Station::has_stationid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestGetStationsInfo_Station::set_has_stationid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestGetStationsInfo_Station::clear_has_stationid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestGetStationsInfo_Station::clear_stationid() {
  stationid_ = 0;
  clear_has_stationid();
}
inline ::google::protobuf::int32 RequestGetStationsInfo_Station::stationid() const {
  return stationid_;
}
inline void RequestGetStationsInfo_Station::set_stationid(::google::protobuf::int32 value) {
  set_has_stationid();
  stationid_ = value;
}

// -------------------------------------------------------------------

// RequestGetStationsInfo

// required int32 protoVersion = 1;
inline bool RequestGetStationsInfo::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestGetStationsInfo::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestGetStationsInfo::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestGetStationsInfo::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 RequestGetStationsInfo::protoversion() const {
  return protoversion_;
}
inline void RequestGetStationsInfo::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// repeated .td.railviz.RequestGetStationsInfo.Station station = 2;
inline int RequestGetStationsInfo::station_size() const {
  return station_.size();
}
inline void RequestGetStationsInfo::clear_station() {
  station_.Clear();
}
inline const ::td::railviz::RequestGetStationsInfo_Station& RequestGetStationsInfo::station(int index) const {
  return station_.Get(index);
}
inline ::td::railviz::RequestGetStationsInfo_Station* RequestGetStationsInfo::mutable_station(int index) {
  return station_.Mutable(index);
}
inline ::td::railviz::RequestGetStationsInfo_Station* RequestGetStationsInfo::add_station() {
  return station_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::RequestGetStationsInfo_Station >&
RequestGetStationsInfo::station() const {
  return station_;
}
inline ::google::protobuf::RepeatedPtrField< ::td::railviz::RequestGetStationsInfo_Station >*
RequestGetStationsInfo::mutable_station() {
  return &station_;
}

// -------------------------------------------------------------------

// ResponseGetStationsInfo_Station

// required string name = 1;
inline bool ResponseGetStationsInfo_Station::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseGetStationsInfo_Station::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseGetStationsInfo_Station::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseGetStationsInfo_Station::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ResponseGetStationsInfo_Station::name() const {
  return *name_;
}
inline void ResponseGetStationsInfo_Station::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ResponseGetStationsInfo_Station::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ResponseGetStationsInfo_Station::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResponseGetStationsInfo_Station::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* ResponseGetStationsInfo_Station::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ResponseGetStationsInfo_Station::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ResponseGetStationsInfo

// required int32 protoVersion = 1;
inline bool ResponseGetStationsInfo::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseGetStationsInfo::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseGetStationsInfo::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseGetStationsInfo::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 ResponseGetStationsInfo::protoversion() const {
  return protoversion_;
}
inline void ResponseGetStationsInfo::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// repeated .td.railviz.ResponseGetStationsInfo.Station station = 2;
inline int ResponseGetStationsInfo::station_size() const {
  return station_.size();
}
inline void ResponseGetStationsInfo::clear_station() {
  station_.Clear();
}
inline const ::td::railviz::ResponseGetStationsInfo_Station& ResponseGetStationsInfo::station(int index) const {
  return station_.Get(index);
}
inline ::td::railviz::ResponseGetStationsInfo_Station* ResponseGetStationsInfo::mutable_station(int index) {
  return station_.Mutable(index);
}
inline ::td::railviz::ResponseGetStationsInfo_Station* ResponseGetStationsInfo::add_station() {
  return station_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseGetStationsInfo_Station >&
ResponseGetStationsInfo::station() const {
  return station_;
}
inline ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseGetStationsInfo_Station >*
ResponseGetStationsInfo::mutable_station() {
  return &station_;
}

// -------------------------------------------------------------------

// RequestAllTrains

// required int32 protoVersion = 1;
inline bool RequestAllTrains::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestAllTrains::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestAllTrains::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestAllTrains::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 RequestAllTrains::protoversion() const {
  return protoversion_;
}
inline void RequestAllTrains::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// -------------------------------------------------------------------

// ResponseAllTrains_Train_Station

// required int32 id = 1;
inline bool ResponseAllTrains_Train_Station::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseAllTrains_Train_Station::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseAllTrains_Train_Station::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseAllTrains_Train_Station::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ResponseAllTrains_Train_Station::id() const {
  return id_;
}
inline void ResponseAllTrains_Train_Station::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required float latitude = 2;
inline bool ResponseAllTrains_Train_Station::has_latitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseAllTrains_Train_Station::set_has_latitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseAllTrains_Train_Station::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseAllTrains_Train_Station::clear_latitude() {
  latitude_ = 0;
  clear_has_latitude();
}
inline float ResponseAllTrains_Train_Station::latitude() const {
  return latitude_;
}
inline void ResponseAllTrains_Train_Station::set_latitude(float value) {
  set_has_latitude();
  latitude_ = value;
}

// required float longitude = 3;
inline bool ResponseAllTrains_Train_Station::has_longitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ResponseAllTrains_Train_Station::set_has_longitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ResponseAllTrains_Train_Station::clear_has_longitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ResponseAllTrains_Train_Station::clear_longitude() {
  longitude_ = 0;
  clear_has_longitude();
}
inline float ResponseAllTrains_Train_Station::longitude() const {
  return longitude_;
}
inline void ResponseAllTrains_Train_Station::set_longitude(float value) {
  set_has_longitude();
  longitude_ = value;
}

// required int32 time = 4;
inline bool ResponseAllTrains_Train_Station::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ResponseAllTrains_Train_Station::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ResponseAllTrains_Train_Station::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ResponseAllTrains_Train_Station::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 ResponseAllTrains_Train_Station::time() const {
  return time_;
}
inline void ResponseAllTrains_Train_Station::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// ResponseAllTrains_Train

// required .td.railviz.ResponseAllTrains.Train.Station start = 1;
inline bool ResponseAllTrains_Train::has_start() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseAllTrains_Train::set_has_start() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseAllTrains_Train::clear_has_start() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseAllTrains_Train::clear_start() {
  if (start_ != NULL) start_->::td::railviz::ResponseAllTrains_Train_Station::Clear();
  clear_has_start();
}
inline const ::td::railviz::ResponseAllTrains_Train_Station& ResponseAllTrains_Train::start() const {
  return start_ != NULL ? *start_ : *default_instance_->start_;
}
inline ::td::railviz::ResponseAllTrains_Train_Station* ResponseAllTrains_Train::mutable_start() {
  set_has_start();
  if (start_ == NULL) start_ = new ::td::railviz::ResponseAllTrains_Train_Station;
  return start_;
}
inline ::td::railviz::ResponseAllTrains_Train_Station* ResponseAllTrains_Train::release_start() {
  clear_has_start();
  ::td::railviz::ResponseAllTrains_Train_Station* temp = start_;
  start_ = NULL;
  return temp;
}
inline void ResponseAllTrains_Train::set_allocated_start(::td::railviz::ResponseAllTrains_Train_Station* start) {
  delete start_;
  start_ = start;
  if (start) {
    set_has_start();
  } else {
    clear_has_start();
  }
}

// required .td.railviz.ResponseAllTrains.Train.Station end = 2;
inline bool ResponseAllTrains_Train::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseAllTrains_Train::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseAllTrains_Train::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseAllTrains_Train::clear_end() {
  if (end_ != NULL) end_->::td::railviz::ResponseAllTrains_Train_Station::Clear();
  clear_has_end();
}
inline const ::td::railviz::ResponseAllTrains_Train_Station& ResponseAllTrains_Train::end() const {
  return end_ != NULL ? *end_ : *default_instance_->end_;
}
inline ::td::railviz::ResponseAllTrains_Train_Station* ResponseAllTrains_Train::mutable_end() {
  set_has_end();
  if (end_ == NULL) end_ = new ::td::railviz::ResponseAllTrains_Train_Station;
  return end_;
}
inline ::td::railviz::ResponseAllTrains_Train_Station* ResponseAllTrains_Train::release_end() {
  clear_has_end();
  ::td::railviz::ResponseAllTrains_Train_Station* temp = end_;
  end_ = NULL;
  return temp;
}
inline void ResponseAllTrains_Train::set_allocated_end(::td::railviz::ResponseAllTrains_Train_Station* end) {
  delete end_;
  end_ = end;
  if (end) {
    set_has_end();
  } else {
    clear_has_end();
  }
}

// -------------------------------------------------------------------

// ResponseAllTrains

// required int32 protoVersion = 1;
inline bool ResponseAllTrains::has_protoversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseAllTrains::set_has_protoversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseAllTrains::clear_has_protoversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseAllTrains::clear_protoversion() {
  protoversion_ = 0;
  clear_has_protoversion();
}
inline ::google::protobuf::int32 ResponseAllTrains::protoversion() const {
  return protoversion_;
}
inline void ResponseAllTrains::set_protoversion(::google::protobuf::int32 value) {
  set_has_protoversion();
  protoversion_ = value;
}

// required int32 currentTime = 2;
inline bool ResponseAllTrains::has_currenttime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseAllTrains::set_has_currenttime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseAllTrains::clear_has_currenttime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseAllTrains::clear_currenttime() {
  currenttime_ = 0;
  clear_has_currenttime();
}
inline ::google::protobuf::int32 ResponseAllTrains::currenttime() const {
  return currenttime_;
}
inline void ResponseAllTrains::set_currenttime(::google::protobuf::int32 value) {
  set_has_currenttime();
  currenttime_ = value;
}

// repeated .td.railviz.ResponseAllTrains.Train trains = 3;
inline int ResponseAllTrains::trains_size() const {
  return trains_.size();
}
inline void ResponseAllTrains::clear_trains() {
  trains_.Clear();
}
inline const ::td::railviz::ResponseAllTrains_Train& ResponseAllTrains::trains(int index) const {
  return trains_.Get(index);
}
inline ::td::railviz::ResponseAllTrains_Train* ResponseAllTrains::mutable_trains(int index) {
  return trains_.Mutable(index);
}
inline ::td::railviz::ResponseAllTrains_Train* ResponseAllTrains::add_trains() {
  return trains_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllTrains_Train >&
ResponseAllTrains::trains() const {
  return trains_;
}
inline ::google::protobuf::RepeatedPtrField< ::td::railviz::ResponseAllTrains_Train >*
ResponseAllTrains::mutable_trains() {
  return &trains_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace railviz
}  // namespace td

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WebsocketService_2eproto__INCLUDED
