const SWAP_LOCATIONS = 'SWAP_LOCATIONS';
const SEARCH_FORM_UPDATE = 'SEARCH_FORM_UPDATE';
const SEARCH_ADD_TRANSPORT = 'SEARCH_ADD_TRANSPORT';
const SEARCH_REMOVE_TRANSPORT = 'SEARCH_REMOVE_TRANSPORT';
const REQUEST_ROUTING = 'REQUEST_ROUTING';
const RECEIVE_ROUTING = 'RECEIVE_ROUTING';
const RESET_QUERY_TO_LAST = 'RESET_QUERY_TO_LAST';
const SELECT_CONNECTION = 'SELECT_CONNECTION';

const actions = {
  SWAP_LOCATIONS,
  SEARCH_FORM_UPDATE,
  SEARCH_ADD_TRANSPORT,
  SEARCH_REMOVE_TRANSPORT,
  REQUEST_ROUTING,
  RECEIVE_ROUTING,
  RESET_QUERY_TO_LAST,
  SELECT_CONNECTION
};

export default actions;
