// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EventInfo extends Table {
  public static EventInfo getRootAsEventInfo(ByteBuffer _bb) { return getRootAsEventInfo(_bb, new EventInfo()); }
  public static EventInfo getRootAsEventInfo(ByteBuffer _bb, EventInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public EventInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long time() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long scheduleTime() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String track() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer trackAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public byte reason() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createEventInfo(FlatBufferBuilder builder,
      long time,
      long schedule_time,
      int trackOffset,
      byte reason) {
    builder.startObject(4);
    EventInfo.addScheduleTime(builder, schedule_time);
    EventInfo.addTime(builder, time);
    EventInfo.addTrack(builder, trackOffset);
    EventInfo.addReason(builder, reason);
    return EventInfo.endEventInfo(builder);
  }

  public static void startEventInfo(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addTime(FlatBufferBuilder builder, long time) { builder.addLong(0, time, 0); }
  public static void addScheduleTime(FlatBufferBuilder builder, long scheduleTime) { builder.addLong(1, scheduleTime, 0); }
  public static void addTrack(FlatBufferBuilder builder, int trackOffset) { builder.addOffset(2, trackOffset, 0); }
  public static void addReason(FlatBufferBuilder builder, byte reason) { builder.addByte(3, reason, 0); }
  public static int endEventInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

