// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Method extends Table {
  public static Method getRootAsMethod(ByteBuffer _bb) { return getRootAsMethod(_bb, new Method()); }
  public static Method getRootAsMethod(ByteBuffer _bb, Method obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Method __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String path() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pathAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String in() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer inAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String out() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer outAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createMethod(FlatBufferBuilder builder,
      int pathOffset,
      int inOffset,
      int outOffset) {
    builder.startObject(3);
    Method.addOut(builder, outOffset);
    Method.addIn(builder, inOffset);
    Method.addPath(builder, pathOffset);
    return Method.endMethod(builder);
  }

  public static void startMethod(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPath(FlatBufferBuilder builder, int pathOffset) { builder.addOffset(0, pathOffset, 0); }
  public static void addIn(FlatBufferBuilder builder, int inOffset) { builder.addOffset(1, inOffset, 0); }
  public static void addOut(FlatBufferBuilder builder, int outOffset) { builder.addOffset(2, outOffset, 0); }
  public static int endMethod(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

