// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class MsgContent {
  private MsgContent() { }
  public static final byte NONE = 0;
  public static final byte ApiDescription = 1;
  public static final byte Connection = 2;
  public static final byte MotisNoMessage = 3;
  public static final byte MotisError = 4;
  public static final byte MotisSuccess = 5;
  public static final byte HTTPRequest = 6;
  public static final byte HTTPResponse = 7;
  public static final byte TripId = 8;
  public static final byte BikesharingRequest = 9;
  public static final byte BikesharingResponse = 10;
  public static final byte BikesharingGeoTerminalsRequest = 11;
  public static final byte BikesharingGeoTerminalsResponse = 12;
  public static final byte StationGuesserRequest = 13;
  public static final byte StationGuesserResponse = 14;
  public static final byte IntermodalRoutingRequest = 15;
  public static final byte LookupGeoStationIdRequest = 16;
  public static final byte LookupGeoStationRequest = 17;
  public static final byte LookupGeoStationResponse = 18;
  public static final byte LookupBatchGeoStationRequest = 19;
  public static final byte LookupBatchGeoStationResponse = 20;
  public static final byte LookupStationEventsRequest = 21;
  public static final byte LookupStationEventsResponse = 22;
  public static final byte LookupScheduleInfoResponse = 23;
  public static final byte LookupMetaStationRequest = 24;
  public static final byte LookupMetaStationResponse = 25;
  public static final byte LookupBatchMetaStationRequest = 26;
  public static final byte LookupBatchMetaStationResponse = 27;
  public static final byte LookupIdTrainRequest = 28;
  public static final byte LookupIdTrainResponse = 29;
  public static final byte PathBoxesResponse = 30;
  public static final byte PathIdTrainRequest = 31;
  public static final byte PathSeqResponse = 32;
  public static final byte PathStationSeqRequest = 33;
  public static final byte RailVizTrainsRequest = 34;
  public static final byte RailVizTrainsResponse = 35;
  public static final byte RailVizTripsRequest = 36;
  public static final byte RailVizStationRequest = 37;
  public static final byte RailVizStationResponse = 38;
  public static final byte OSRMOneToManyRequest = 39;
  public static final byte OSRMOneToManyResponse = 40;
  public static final byte OSRMViaRouteRequest = 41;
  public static final byte OSRMViaRouteResponse = 42;
  public static final byte OSRMSmoothViaRouteRequest = 43;
  public static final byte OSRMSmoothViaRouteResponse = 44;
  public static final byte ReliableRoutingRequest = 45;
  public static final byte ReliableRoutingResponse = 46;
  public static final byte ReliabilityRatingResponse = 47;
  public static final byte RISBatch = 48;
  public static final byte RISForwardTimeRequest = 49;
  public static final byte RoutingRequest = 50;
  public static final byte RoutingResponse = 51;
  public static final byte RtUpdate = 52;
  public static final byte RailVizTripGuessRequest = 53;
  public static final byte RailVizTripGuessResponse = 54;
  public static final byte AddressRequest = 55;
  public static final byte AddressResponse = 56;

  private static final String[] names = { "NONE", "ApiDescription", "Connection", "MotisNoMessage", "MotisError", "MotisSuccess", "HTTPRequest", "HTTPResponse", "TripId", "BikesharingRequest", "BikesharingResponse", "BikesharingGeoTerminalsRequest", "BikesharingGeoTerminalsResponse", "StationGuesserRequest", "StationGuesserResponse", "IntermodalRoutingRequest", "LookupGeoStationIdRequest", "LookupGeoStationRequest", "LookupGeoStationResponse", "LookupBatchGeoStationRequest", "LookupBatchGeoStationResponse", "LookupStationEventsRequest", "LookupStationEventsResponse", "LookupScheduleInfoResponse", "LookupMetaStationRequest", "LookupMetaStationResponse", "LookupBatchMetaStationRequest", "LookupBatchMetaStationResponse", "LookupIdTrainRequest", "LookupIdTrainResponse", "PathBoxesResponse", "PathIdTrainRequest", "PathSeqResponse", "PathStationSeqRequest", "RailVizTrainsRequest", "RailVizTrainsResponse", "RailVizTripsRequest", "RailVizStationRequest", "RailVizStationResponse", "OSRMOneToManyRequest", "OSRMOneToManyResponse", "OSRMViaRouteRequest", "OSRMViaRouteResponse", "OSRMSmoothViaRouteRequest", "OSRMSmoothViaRouteResponse", "ReliableRoutingRequest", "ReliableRoutingResponse", "ReliabilityRatingResponse", "RISBatch", "RISForwardTimeRequest", "RoutingRequest", "RoutingResponse", "RtUpdate", "RailVizTripGuessRequest", "RailVizTripGuessResponse", "AddressRequest", "AddressResponse", };

  public static String name(int e) { return names[e]; }
};

