// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class MsgContent {
  private MsgContent() { }
  public static final byte NONE = 0;
  public static final byte ApiDescription = 1;
  public static final byte Connection = 2;
  public static final byte MotisNoMessage = 3;
  public static final byte MotisError = 4;
  public static final byte MotisSuccess = 5;
  public static final byte HTTPRequest = 6;
  public static final byte HTTPResponse = 7;
  public static final byte TripId = 8;
  public static final byte BikesharingRequest = 9;
  public static final byte BikesharingResponse = 10;
  public static final byte BikesharingGeoTerminalsRequest = 11;
  public static final byte BikesharingGeoTerminalsResponse = 12;
  public static final byte StationGuesserRequest = 13;
  public static final byte StationGuesserResponse = 14;
  public static final byte IntermodalRoutingRequest = 15;
  public static final byte IntermodalRoutingResponse = 16;
  public static final byte LookupGeoStationIdRequest = 17;
  public static final byte LookupGeoStationRequest = 18;
  public static final byte LookupGeoStationResponse = 19;
  public static final byte LookupBatchGeoStationRequest = 20;
  public static final byte LookupBatchGeoStationResponse = 21;
  public static final byte LookupStationEventsRequest = 22;
  public static final byte LookupStationEventsResponse = 23;
  public static final byte LookupScheduleInfoResponse = 24;
  public static final byte LookupMetaStationRequest = 25;
  public static final byte LookupMetaStationResponse = 26;
  public static final byte LookupBatchMetaStationRequest = 27;
  public static final byte LookupBatchMetaStationResponse = 28;
  public static final byte LookupIdTrainRequest = 29;
  public static final byte LookupIdTrainResponse = 30;
  public static final byte RoutesIdTrainRequest = 31;
  public static final byte RoutesIdTrainResponse = 32;
  public static final byte RailVizTrainsRequest = 33;
  public static final byte RailVizTrainsResponse = 34;
  public static final byte RailVizTripsRequest = 35;
  public static final byte OSRMOneToManyRequest = 36;
  public static final byte OSRMOneToManyResponse = 37;
  public static final byte OSRMViaRouteRequest = 38;
  public static final byte OSRMViaRouteResponse = 39;
  public static final byte OSRMSmoothViaRouteRequest = 40;
  public static final byte OSRMSmoothViaRouteResponse = 41;
  public static final byte ReliableRoutingRequest = 42;
  public static final byte ReliableRoutingResponse = 43;
  public static final byte ReliabilityRatingResponse = 44;
  public static final byte RISBatch = 45;
  public static final byte RISForwardTimeRequest = 46;
  public static final byte RoutingRequest = 47;
  public static final byte RoutingResponse = 48;
  public static final byte RtUpdate = 49;

  private static final String[] names = { "NONE", "ApiDescription", "Connection", "MotisNoMessage", "MotisError", "MotisSuccess", "HTTPRequest", "HTTPResponse", "TripId", "BikesharingRequest", "BikesharingResponse", "BikesharingGeoTerminalsRequest", "BikesharingGeoTerminalsResponse", "StationGuesserRequest", "StationGuesserResponse", "IntermodalRoutingRequest", "IntermodalRoutingResponse", "LookupGeoStationIdRequest", "LookupGeoStationRequest", "LookupGeoStationResponse", "LookupBatchGeoStationRequest", "LookupBatchGeoStationResponse", "LookupStationEventsRequest", "LookupStationEventsResponse", "LookupScheduleInfoResponse", "LookupMetaStationRequest", "LookupMetaStationResponse", "LookupBatchMetaStationRequest", "LookupBatchMetaStationResponse", "LookupIdTrainRequest", "LookupIdTrainResponse", "RoutesIdTrainRequest", "RoutesIdTrainResponse", "RailVizTrainsRequest", "RailVizTrainsResponse", "RailVizTripsRequest", "OSRMOneToManyRequest", "OSRMOneToManyResponse", "OSRMViaRouteRequest", "OSRMViaRouteResponse", "OSRMSmoothViaRouteRequest", "OSRMSmoothViaRouteResponse", "ReliableRoutingRequest", "ReliableRoutingResponse", "ReliabilityRatingResponse", "RISBatch", "RISForwardTimeRequest", "RoutingRequest", "RoutingResponse", "RtUpdate", };

  public static String name(int e) { return names[e]; }
};

