// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class MsgContent {
  private MsgContent() { }
  public static final byte NONE = 0;
  public static final byte Connection = 1;
  public static final byte MotisNoMessage = 2;
  public static final byte MotisError = 3;
  public static final byte MotisSuccess = 4;
  public static final byte HTTPRequest = 5;
  public static final byte HTTPResponse = 6;
  public static final byte TripId = 7;
  public static final byte BikesharingRequest = 8;
  public static final byte BikesharingResponse = 9;
  public static final byte BikesharingGeoTerminalsRequest = 10;
  public static final byte BikesharingGeoTerminalsResponse = 11;
  public static final byte StationGuesserRequest = 12;
  public static final byte StationGuesserResponse = 13;
  public static final byte IntermodalRoutingRequest = 14;
  public static final byte IntermodalRoutingResponse = 15;
  public static final byte LookupGeoStationIdRequest = 16;
  public static final byte LookupGeoStationRequest = 17;
  public static final byte LookupGeoStationResponse = 18;
  public static final byte LookupBatchGeoStationRequest = 19;
  public static final byte LookupBatchGeoStationResponse = 20;
  public static final byte LookupStationEventsRequest = 21;
  public static final byte LookupStationEventsResponse = 22;
  public static final byte LookupScheduleInfoResponse = 23;
  public static final byte LookupMetaStationRequest = 24;
  public static final byte LookupMetaStationResponse = 25;
  public static final byte LookupBatchMetaStationRequest = 26;
  public static final byte LookupBatchMetaStationResponse = 27;
  public static final byte LookupIdTrainRequest = 28;
  public static final byte LookupIdTrainResponse = 29;
  public static final byte RoutesIdTrainRequest = 30;
  public static final byte RoutesIdTrainResponse = 31;
  public static final byte RailVizInit = 32;
  public static final byte RailVizAlltraReq = 33;
  public static final byte RailVizAlltraRes = 34;
  public static final byte RailVizStationDetailReq = 35;
  public static final byte RailVizStationDetailRes = 36;
  public static final byte RailVizRouteAtTimeReq = 37;
  public static final byte RailVizRouteAtTimeRes = 38;
  public static final byte RailVizFindTrain = 39;
  public static final byte OSRMOneToManyRequest = 40;
  public static final byte OSRMOneToManyResponse = 41;
  public static final byte OSRMViaRouteRequest = 42;
  public static final byte OSRMViaRouteResponse = 43;
  public static final byte OSRMSmoothViaRouteRequest = 44;
  public static final byte OSRMSmoothViaRouteResponse = 45;
  public static final byte ReliableRoutingRequest = 46;
  public static final byte ReliableRoutingResponse = 47;
  public static final byte ReliabilityRatingResponse = 48;
  public static final byte RISBatch = 49;
  public static final byte RISForwardTimeRequest = 50;
  public static final byte RoutingRequest = 51;
  public static final byte RoutingResponse = 52;
  public static final byte RtUpdate = 53;

  private static final String[] names = { "NONE", "Connection", "MotisNoMessage", "MotisError", "MotisSuccess", "HTTPRequest", "HTTPResponse", "TripId", "BikesharingRequest", "BikesharingResponse", "BikesharingGeoTerminalsRequest", "BikesharingGeoTerminalsResponse", "StationGuesserRequest", "StationGuesserResponse", "IntermodalRoutingRequest", "IntermodalRoutingResponse", "LookupGeoStationIdRequest", "LookupGeoStationRequest", "LookupGeoStationResponse", "LookupBatchGeoStationRequest", "LookupBatchGeoStationResponse", "LookupStationEventsRequest", "LookupStationEventsResponse", "LookupScheduleInfoResponse", "LookupMetaStationRequest", "LookupMetaStationResponse", "LookupBatchMetaStationRequest", "LookupBatchMetaStationResponse", "LookupIdTrainRequest", "LookupIdTrainResponse", "RoutesIdTrainRequest", "RoutesIdTrainResponse", "RailVizInit", "RailVizAlltraReq", "RailVizAlltraRes", "RailVizStationDetailReq", "RailVizStationDetailRes", "RailVizRouteAtTimeReq", "RailVizRouteAtTimeRes", "RailVizFindTrain", "OSRMOneToManyRequest", "OSRMOneToManyResponse", "OSRMViaRouteRequest", "OSRMViaRouteResponse", "OSRMSmoothViaRouteRequest", "OSRMSmoothViaRouteResponse", "ReliableRoutingRequest", "ReliableRoutingResponse", "ReliabilityRatingResponse", "RISBatch", "RISForwardTimeRequest", "RoutingRequest", "RoutingResponse", "RtUpdate", };

  public static String name(int e) { return names[e]; }
};

