// automatically generated by the FlatBuffers compiler, do not modify

package motis.address;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AddressRequest extends Table {
  public static AddressRequest getRootAsAddressRequest(ByteBuffer _bb) { return getRootAsAddressRequest(_bb, new AddressRequest()); }
  public static AddressRequest getRootAsAddressRequest(ByteBuffer _bb, AddressRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public AddressRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String input() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer inputAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createAddressRequest(FlatBufferBuilder builder,
      int inputOffset) {
    builder.startObject(1);
    AddressRequest.addInput(builder, inputOffset);
    return AddressRequest.endAddressRequest(builder);
  }

  public static void startAddressRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addInput(FlatBufferBuilder builder, int inputOffset) { builder.addOffset(0, inputOffset, 0); }
  public static int endAddressRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

