// automatically generated by the FlatBuffers compiler, do not modify

package motis.address;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AddressResponse extends Table {
  public static AddressResponse getRootAsAddressResponse(ByteBuffer _bb) { return getRootAsAddressResponse(_bb, new AddressResponse()); }
  public static AddressResponse getRootAsAddressResponse(ByteBuffer _bb, AddressResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public AddressResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Address guesses(int j) { return guesses(new Address(), j); }
  public Address guesses(Address obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int guessesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createAddressResponse(FlatBufferBuilder builder,
      int guessesOffset) {
    builder.startObject(1);
    AddressResponse.addGuesses(builder, guessesOffset);
    return AddressResponse.endAddressResponse(builder);
  }

  public static void startAddressResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addGuesses(FlatBufferBuilder builder, int guessesOffset) { builder.addOffset(0, guessesOffset, 0); }
  public static int createGuessesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGuessesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endAddressResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

