// automatically generated by the FlatBuffers compiler, do not modify

package motis.address;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Region extends Table {
  public static Region getRootAsRegion(ByteBuffer _bb) { return getRootAsRegion(_bb, new Region()); }
  public static Region getRootAsRegion(ByteBuffer _bb, Region obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Region __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long adminLevel() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }

  public static int createRegion(FlatBufferBuilder builder,
      int nameOffset,
      long admin_level) {
    builder.startObject(2);
    Region.addAdminLevel(builder, admin_level);
    Region.addName(builder, nameOffset);
    return Region.endRegion(builder);
  }

  public static void startRegion(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addAdminLevel(FlatBufferBuilder builder, long adminLevel) { builder.addInt(1, (int)adminLevel, 0); }
  public static int endRegion(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

